/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package aao_knapsack.problem;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;


class AppTest {
    private final int weight = 1000;

//    @Test
//    public void Test_TC_1() {
//        Kanpsack problem = new Kanpsack();
//        int n = 4;
//        int W[] = new int[4];
//        int V[] = new int[4];
//
//        assertEquals(7926, problem.knapsackDyProg(W, V, weight, n));
//    }
//
//    @Test
//    public void Test_TC_2() {
//        Kanpsack problem = new Kanpsack();
//        int n = 8;
//        int W[] = new int[8];
//        int V[] = new int[8];
//
//        assertEquals(15516, problem.knapsackDyProg(W, V, weight, n));
//    }
//
//    @Test
//    public void Test_TC_3() {
//        Kanpsack problem = new Kanpsack();
//        int n = 16;
//        int W[] = new int[16];
//        int V[] = new int[16];
//
//        Assertions.assertEquals(49232, problem.knapsackDyProg(W, V, weight, n));
//    }

//    @Test
//    public void Test_Tc_4() {
//        Kanpsack problem = new Kanpsack();
//        String res = problem.classify();
//        Assertions.assertEquals(res, "Linear order");
//    }
}
